### ISSUE TITLE
while creating organization-rule-set it is not working as expected

### ISSUE THREAD

**Issue by A660988** [crossplane-contrib/provider-upjet-github#86]
Hello I am trying to create organizatio rule set.

I am giving the hard coded value in the following compoition

![image](https://github.com/user-attachments/assets/c2d9d77f-089b-497f-9a7d-b902141e9737)
    
    Wgen we apply claim, seems it is not creating the ruleset as expected. 
    **The value I am providing to parameter name **condition** that is not working.**
    ```
    Example 
    conditions:
              - ref_name:
                  - include: 
                     - ~ALL     
                  - exclude:
                     - "refs/heads/dev*"
              - repository_name:
                  - include:
                     - epis-events
                     - epis-dev-services-library
     ```

           
    
![image](https://github.com/user-attachments/assets/55175f26-5bd5-4667-9256-a4a081c21601)

  Can you please look into this and suggest what is wrong here?

Thanks in Advance
