### ISSUE TITLE
Addng app as a forcePushBypassers 

### ISSUE THREAD

**Issue by KALAKATASUNEETHA** [crossplane-contrib/provider-upjet-github#88]
I am trying to add app as a forcePushBypassers
```

`spec:
      forProvider:
        allowsDeletions: false
        enforceAdmins: true
        forcePushBypassers:
        - /appName`
```

Its not adding app as a bypasser. 

There is no document with example.
Can you provide example how to add an app ? Is there dependency fields need to set?
